import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Regatta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="nb">
      <body>
        <nav>
          <Link href="/">Home </Link>
          <Link href="/dashboard">Dashboard</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
