import './globals.css'
import Header from './header'

export const metadata = {
  title: 'Regatta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="nb">
      <body>
        {/* @ts-expect-error Server Component */}
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
